name: Upload charm to charmhub

on:
  push:
    branches:
      - "main"

jobs:
  charmhub-upload:
    runs-on: ubuntu-20.04
    name: Charmhub upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check libraries
        uses: canonical/charming-actions/check-libraries@latest
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@latest
        id: channel

      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@latest
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          upload-image: "false"
          channel: "${{ steps.channel.outputs.name }}"
